kafka_controller:
  hosts:
    con1:
    

kafka_broker:
  hosts:
    con2:
    con7:
  vars:
    kafka_broker_custom_listeners:
      service_listener:
        name: SERVICE
        ssl_enabled: false
        ssl_mutual_auth_enabled: false
        sasl_protocol: plain
    kafka_broker_custom_properties:
      listener.name.service.plain.sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required;

schema_registry:
  hosts:
    con3:

kafka_connect:
  hosts:
    con4:

control_center:
  hosts:
    con5:
    
ksql:
  hosts:
    con6:

all:
  vars:
    validate_hosts: true
    ansible_connection: ssh
    ansible_user: root
#    ansible_become: true
    ansible_ssh_pass: root123
    jmxexporter_enabled: true
    jolokia_enabled: true
    kafka_broker_configure_multiple_listeners: false
    ssl_enabled: false
    schema_registry_ssl_enabled: false
    sasl_protocol: plain
    mds_retries: 5
    sasl_plain_users:
      admin:
        principal: 'admin'
        password: 'admin-secret'
      schema_registry:
        principal: 'schema_registry'
        password: 'schema_registry-secret'
      kafka_connect:
        principal: 'kafka_connect'
        password: 'kafka_connect-secret'
      ksql:
        principal: 'ksql'
        password: 'ksql-secret'
      kafka_rest:
        principal: 'kafka_rest'
        password: 'kafka_rest-secret'
      control_center:
        principal: 'control_center'
        password: 'control_center-secret'
    ksql_log_streaming_enabled: true
    kafka_controller_custom_properties:
      log.dirs: /var/dataa
    kafka_controller_sasl_protocol: plain
    kafka_broker_custom_properties:
      listener.name.service.plain.sasl.jaas.config: org.apache.kafka.common.security.plain.PlainLoginModule required;

      